react_app:
    path: /app/{reactRouting}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: base.html.twig
    requirements:
        reactRouting: '.+'
